app/Http/routes.php
<?php

# ------------------ Page Route ------------------------
Route::get('/', 'PagesController@home')->name('home');
Route::get('/about', 'PagesController@about')->name('about');
Route::get('/search', 'PagesController@search')->name('search');
Route::get('/feed', 'PagesController@feed')->name('feed');
Route::get('/sitemap', 'PagesController@sitemap');
Route::get('/sitemap.xml', 'PagesController@sitemap');

# ------------------ User stuff ------------------------

Route::get('/users/{id}/replies', 'UsersController@replies')->name('users.replies');
Route::get('/users/{id}/topics', 'UsersController@topics')->name('users.topics');
Route::get('/users/{id}/favorites', 'UsersController@favorites')->name('users.favorites');
Route::get('/users/{id}/following', 'UsersController@following')->name('users.following');
Route::get('/users/{id}/refresh_cache', 'UsersController@refreshCache')->name('users.refresh_cache');
Route::get('/users/{id}/access_tokens', 'UsersController@accessTokens')->name('users.access_tokens');
Route::get('/access_token/{token}/revoke', 'UsersController@revokeAccessToken')->name('users.access_tokens.revoke');
Route::get('/users/regenerate_login_token', 'UsersController@regenerateLoginToken')->name('users.regenerate_login_token');
Route::post('/users/follow/{id}', 'UsersController@doFollow')->name('users.doFollow');
Route::get('/users/{id}/edit_email_notify', 'UsersController@editEmailNotify')->name('users.edit_email_notify');
Route::post('/users/{id}/update_email_notify', 'UsersController@updateEmailNotify')->name('users.update_email_notify');
Route::get('/users/{id}/edit_social_binding', 'UsersController@editSocialBinding')->name('users.edit_social_binding');

Route::get('/users', 'UsersController@index')->name('users.index');
Route::get('/users/create', 'UsersController@create')->name('users.create');
Route::post('/users', 'UsersController@store')->name('users.store');
Route::get('/users/{id}', 'UsersController@show')->name('users.show');
Route::get('/users/{id}/edit', 'UsersController@edit')->name('users.edit');
Route::patch('/users/{id}', 'UsersController@update')->name('users.update');
Route::delete('/users/{id}', 'UsersController@destroy')->name('users.destroy');
Route::get('/users/{id}/edit_avatar', 'UsersController@editAvatar')->name('users.edit_avatar');
Route::patch('/users/{id}/update_avatar', 'UsersController@updateAvatar')->name('users.update_avatar');

Route::group(['middleware' => 'auth'], function () {
    Route::post('/favorites/{id}', 'FavoritesController@createOrDelete')->name('favorites.createOrDelete');
    Route::get('/notifications', 'NotificationsController@index')->name('notifications.index');
    Route::get('/notifications/count', 'NotificationsController@count')->name('notifications.count');
    Route::post('/attentions/{id}', 'AttentionsController@createOrDelete')->name('attentions.createOrDelete');
});

Route::post('/users/send-verification-mail', 'UsersController@sendVerificationMail')->name('users.send-verification-mail');

# ------------------ Authentication ------------------------

Route::get('/login', 'Auth\AuthController@oauth')->name('login');
Route::get('/login-required', 'Auth\AuthController@loginRequired')->name('login-required');
Route::get('/email-verification-required', 'Auth\AuthController@emailVerificationRequired')->name('email-verification-required');
Route::get('/admin-required', 'Auth\AuthController@adminRequired')->name('admin-required');
Route::get('/user-banned', 'Auth\AuthController@userBanned')->name('user-banned');
Route::get('/signup', 'Auth\AuthController@create')->name('signup');
Route::post('/signup', 'Auth\AuthController@store')->name('signup');
Route::get('/logout', 'Auth\AuthController@logout')->name('logout');
Route::get('/oauth', 'Auth\AuthController@getOauth');

Route::get('/auth/oauth', 'Auth\AuthController@oauth')->name('auth.oauth');
Route::get('/auth/callback', 'Auth\AuthController@callback')->name('auth.callback');
Route::get('/verification/{token}', 'Auth\AuthController@getVerification')->name('verification');

# ------------------ Categories ------------------------

Route::get('categories/{id}', 'CategoriesController@show')->name('categories.show');

# ------------------ Replies ------------------------

Route::post('/replies', 'RepliesController@store')->name('replies.store');
Route::delete('replies/delete/{id}', 'RepliesController@destroy')->name('replies.destroy')->middleware('auth');

# ------------------ Topic ------------------------
Route::get('/topics', 'TopicsController@index')->name('topics.index');
Route::get('/topics/create', 'TopicsController@create')->name('topics.create');
Route::post('/topics', 'TopicsController@store')->name('topics.store');
Route::get('/topics/{id}', 'TopicsController@show')->name('topics.show');
Route::get('/topics/{id}/edit', 'TopicsController@edit')->name('topics.edit');
Route::patch('/topics/{id}', 'TopicsController@update')->name('topics.update');
Route::delete('/topics/{id}', 'TopicsController@destroy')->name('topics.destroy');
Route::post('/topics/{id}/append', 'TopicsController@append')->name('topics.append');

# ------------------ Votes ------------------------

Route::group(['before' => 'auth'], function () {
    Route::post('/topics/{id}/upvote', 'TopicsController@upvote')->name('topics.upvote');
    Route::post('/topics/{id}/downvote', 'TopicsController@downvote')->name('topics.downvote');
    Route::post('/replies/{id}/vote', 'RepliesController@vote')->name('replies.vote');
});

# ------------------ Admin Route ------------------------

Route::group(['before' => 'manage_topics'], function () {
    Route::post('topics/recommend/{id}', 'TopicsController@recommend')->name('topics.recommend');
    Route::post('topics/pin/{id}', 'TopicsController@pin')->name('topics.pin');
    Route::delete('topics/delete/{id}', 'TopicsController@destroy')->name('topics.destroy');
    Route::post('topics/sink/{id}', 'TopicsController@sink')->name('topics.sink');
});

Route::group(['before' => 'manage_users'], function () {
    Route::post('users/blocking/{id}', 'UsersController@blocking')->name('users.blocking');
});

Route::post('/upload_image', 'TopicsController@uploadImage')->name('upload_image')->middleware('auth');

// Health Checking
Route::get('heartbeat', function () {
    return Category::first();
});

Route::get('/github-api-proxy/users/{username}', 'UsersController@githubApiProxy')->name('users.github-api-proxy');
Route::get('/github-card', 'UsersController@githubCard')->name('users.github-card');

Route::group(['middleware' => ['auth', 'admin_auth']], function () {
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Laracasts\Presenter\PresentableTrait;
use Venturecraft\Revisionable\RevisionableTrait;
use Smartisan\Follow\FollowTrait;
use App\Jobs\SendActivateMail;
use App\Models\Traits\UserRememberTokenHelper;
use App\Models\Traits\UserSocialiteHelper;
use App\Models\Traits\UserAvatarHelper;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract
{
    use UserRememberTokenHelper,UserSocialiteHelper,UserAvatarHelper;
    use PresentableTrait;
    public $presenter = 'Phphub\Presenters\UserPresenter';

    // For admin log
    use RevisionableTrait;
    protected $keepRevisionOf = [
        'is_banned'
    ];

    use EntrustUserTrait {
        restore as private restoreEntrust;
        EntrustUserTrait::can as may;
    }
    use SoftDeletes { restore as private restoreSoftDelete; }
    use FollowTrait;
    protected $dates = ['deleted_at'];

    protected $table   = 'users';
    protected $guarded = ['id', 'is_banned'];

    public static function boot()
    {
        parent::boot();

        static::created(function ($user) {
            $driver = $user['github_id'] ? 'github' : 'weixin';
            SiteStatus::newUser($driver);

            dispatch(new SendActivateMail($user));
        });
    }

    /**
     * For EntrustUserTrait and SoftDeletes conflict
     */
    public function restore()
    {
        $this->restoreEntrust();
        $this->restoreSoftDelete();
    }

    public function favoriteTopics()
    {
        return $this->belongsToMany(Topic::class, 'favorites')->withTimestamps();
    }

    public function attentTopics()
    {
        return $this->belongsToMany(Topic::class, 'attentions')->withTimestamps();
    }

    public function topics()
    {
        return $this->hasMany(Topic::class);
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function notifications()
    {
        return $this->hasMany(Notification::class)->recent()->with('topic', 'fromUser')->paginate(20);
    }

    public function scopeRecent($query)
    {
        return $query->orderBy('created_at', 'desc');
    }

    public function getIntroductionAttribute($value)
    {
        return str_limit($value, 68);
    }

    public function getPersonalWebsiteAttribute($value)
    {
        return str_replace(['https://', 'http://'], '', $value);
    }

    /**
     * ----------------------------------------
     * UserInterface
     * ----------------------------------------
     */

    public function getAuthIdentifier()
    {
        return $this->getKey();
    }

    public function getAuthPassword()
    {
        return $this->password;
    }
}

resources/views/users/partials/basicinfo.blade.php
<div class="padding-md">
    <div style="text-align: center;">

        @if ($currentUser && $currentUser->id == $user->id)
        <a class="avatar-edit" href="{{ route('users.edit_avatar', $user->id) }}">
            <i class="fa fa-pencil-square"></i>
        </a>
        @endif

        <img src="{{ $user->present()->gravatar(380) }}" class="img-thumbnail users-show-avatar" style="width:100%;margin: 4px 0px 15px;min-height:190px">

    </div>

    <dl class="dl-horizontal">

      <dt><lable>&nbsp; </lable></dt><dd> {{ lang('User ID:') }} {{ $user->id }}</dd>

      <dt><label>Name:</label></dt><dd><strong>{{{ $user->name }}}</strong></dd>

      @if ($user->present()->hasBadge())
        <dt><label>Role:</label></dt><dd><span class="label label-warning">{{{ $user->present()->badgeName() }}}</span></dd>
      @endif

      @if ($user->real_name)
        <dt class="adr"><label> {{ lang('Real Name') }}:</label></dt><dd><span class="org">{{{ $user->real_name }}}</span></dd>
      @endif

      @if ($user->github_name)
      <dt><label>GitHub:</label></dt>
      <dd>
        <a href="https://github.com/{{ $user->github_name }}" target="_blank">
          <i class="fa fa-github-alt"></i> {{ $user->github_name }}
        </a>
      </dd>
      @endif

      @if ($user->company)
        <dt class="adr"><label> {{ lang('Company') }}:</label></dt><dd><span class="org">{{{ $user->company }}}</span></dd>
      @endif

      @if ($user->city)
        <dt class="adr"><label> {{ lang('City') }}:</label></dt><dd><span class="org"><i class="fa fa-map-marker"></i> {{{ $user->city }}}</span></dd>
      @endif

      @if ($user->weibo_id)
      <dt><label><span>{{ lang('Weibo') }}</span>:</label></dt>
      <dd>
        <a href="http://weibo.com/u/{{ $user->weibo_id }}" rel="nofollow" class="weibo" target="_blank"><i class="fa fa-weibo"></i> {{{ $user->weibo_name }}}
        </a>
      </dd>
      @endif

      @if ($user->twitter_account)
      <dt><label><span>Twitter</span>:</label></dt>
      <dd>
        <a href="https://twitter.com/{{ $user->twitter_account }}" rel="nofollow" class="twitter" target="_blank"><i class="fa fa-twitter"></i> {{{ $user->twitter_account }}}
        </a>
      </dd>
      @endif

      @if ($user->personal_website)
      <dt><label>{{ lang('Blog') }}:</label></dt>
      <dd>
        <a href="http://{{ $user->personal_website }}" rel="nofollow" target="_blank" class="url">
          <i class="fa fa-globe"></i> {{{ str_limit($user->personal_website, 22) }}}
        </a>
      </dd>
      @endif

      <dt>
        <label>Since:</label>
      </dt>
      <dd><span>{{ $user->created_at }}</span></dd>
    </dl>
    <div class="clearfix"></div>

    @if ($currentUser && ($currentUser->id == $user->id || Entrust::can('manage_users')))
      <a class="btn btn-primary btn-block" href="{{ route('users.edit', $user->id) }}" id="user-edit-button">
        <i class="fa fa-edit"></i> {{ lang('Edit Profile') }}
      </a>
    @endif

    @if(Auth::check() && $currentUser->id != $user->id)
    <!--{{$isFollowing= $currentUser && $currentUser->isFollowing($user->id) ? true : false}}-->

    <a data-method="post" class="btn btn-{{ !$isFollowing ? 'warning' : 'danger' }} btn-block" href="javascript:void(0);" data-url="{{ route('users.doFollow', $user->id) }}" id="user-edit-button">
       <i class="fa {{!$isFollowing ? 'fa-plus' : 'fa-minus'}}"></i> {{ !$isFollowing ? lang('Follow') : lang('Unfollow') }}
    </a>
    @endif

    @if ($currentUser && Entrust::can('manage_users') && ($currentUser->id != $user->id))
      <a data-method="post" class="btn btn-{{ $user->is_banned == 'yes' ? 'warning' : 'danger' }} btn-block" href="javascript:void(0);" data-url="{{ route('users.blocking', $user->id) }}" id="user-edit-button" onclick=" return confirm('{{ lang('Are you sure want to '. ($user->is_banned == 'yes' ? 'unblock' : 'block') . ' this User?') }}')">
        <i class="fa fa-times"></i> {{ $user->is_banned == 'yes' ? lang('Unblock User') : lang('Block User') }}
      </a>
    @endif

    {{-- @if(Auth::check() && Auth::id() == $user->id)
      @include('users.partials.login_QR')
    @endif --}}

</div>

resources/views/users/partials/following.blade.php
<ul class="list-group">

  @foreach ($followingUsers as $index => $followingUser)
   <li class="list-group-item" >

      <a href="{{ route('users.show', [$followingUser->id]) }}" title="{{{ $followingUser->name }}}">

        <!-- <img class="avatar-topnav" alt="{{{ $followingUser->name }}}" src=""> -->
        <img class="media-object img-thumbnail avatar avatar-small inline-block " src="{{ $followingUser->present()->gravatar }}">

        {{{ $followingUser->name }}}
      </a>

        @if($followingUser->introduction)
        <span class="introduction">
             - {{{ $followingUser->introduction }}}
        </span>
        @endif

  </li>
  @endforeach

</ul>

resources/views/users/partials/infonav.blade.php
<ul class="nav nav-tabs user-info-nav" role="tablist">
  <li class="{{ navViewActive('users.show') }}">
  	<a href="{{ route('users.show', $user->id) }}" >{{ lang('GitHub Info') }}</a>
  </li>
  <li class="{{ navViewActive('users.following') }}">
  	<a href="{{ route('users.following', $user->id) }}" >{{ lang('Following User') }}</a>
  </li>
  <li class="{{ navViewActive('users.topics') }}">
  	<a href="{{ route('users.topics', $user->id) }}" >{{ lang('Posted Topics') }}</a>
  </li>
  <li class="{{ navViewActive('users.replies') }}">
  	<a href="{{ route('users.replies', $user->id) }}" >{{ lang('Replies') }}</a>
  </li>
  <li class="{{ navViewActive('users.favorites') }}">
  	<a href="{{ route('users.favorites', $user->id) }}" >{{ lang('Favorites') }}</a>
  </li>
  @if(Auth::check() && Auth::id() == $user->id)
  <!-- <li class="{{ navViewActive('users.access_tokens') }}">
    <a href="{{ route('users.access_tokens', $user->id) }}" >{{ lang('Access Tokens') }}</a>
  </li> -->
  @endif
</ul>

resources/views/users/partials/login_QR.blade.php
<div style="text-align: center; margin: 20px 0 15px">
  <p style="margin-bottom: 10px">客户端登录二维码</p>
  <img style="height: 180px; width=180px;" " src="data:image/png;base64,{{ base64_encode($user->present()->loginQR(180)) }}">
  <br/><br/>
  <a href="{{ route('users.regenerate_login_token') }}">
  	<button class="btn btn-sm btn-default">重新生成</button> 
  </a>
</div>

resources/views/users/partials/replies.blade.php
<ul class="list-group">
  @foreach ($replies as $index => $reply)
   <li class="list-group-item">

    @if (count($reply->topic))
      <a href="{{ route('topics.show', [$reply->topic_id]) }}" title="{{{ $reply->topic->title }}}" class="remove-padding-left">
          {{{ $reply->topic->title }}}
      </a>
      <span class="meta">
         at <span class="timeago" title="{{ $reply->created_at }}">{{ $reply->created_at }}</span>
      </span>
      <div class="reply-body markdown-reply content-body">
{!! $reply->body !!}
      </div>
    @else
      <div class="deleted text-center">{{ lang('Data has been deleted.') }}</div>
    @endif

  </li>
  @endforeach
</ul>

resources/views/users/partials/setting_nav.blade.php
<div class="padding-md">
    <div class="list-group text-center">
      <a href="{{ route('users.edit', $currentUser->id) }}" class="list-group-item {{ navViewActive('users.edit') }}">
          <i class="text-md fa fa-list-alt" aria-hidden="true"></i>
          &nbsp;{{ lang('Basic Info') }}
      </a>
      <a href="{{ route('users.edit_avatar', $currentUser->id) }}" class="list-group-item {{ navViewActive('users.edit_avatar') }}">
          <i class="text-md fa fa-picture-o" aria-hidden="true"></i>
           &nbsp;{{ lang('Change Avatar') }}
       </a>
      <a href="{{ route('users.edit_email_notify', $currentUser->id) }}" class="list-group-item {{ navViewActive('users.edit_email_notify') }}">
          <i class="text-md fa fa-bell" aria-hidden="true"></i>
          &nbsp;{{ lang('Notification Settings') }}
      </a>
      <a href="{{ route('users.edit_social_binding', $currentUser->id) }}" class="list-group-item {{ navViewActive('users.edit_social_binding') }}">
          <i class="text-md fa fa-flask" aria-hidden="true"></i>
          &nbsp;{{ lang('Social Account Binding') }}
      </a>
    </div>
</div>

resources/views/users/partials/topics.blade.php
<ul class="list-group">

  @foreach ($topics as $index => $topic)
   <li class="list-group-item" >

      <a href="{{ route('topics.show', [$topic->id]) }}" title="{{{ $topic->title }}}">
        {{{ str_limit($topic->title, '100') }}}
      </a>

      <span class="meta">

        <a href="{{ route('categories.show', [$topic->category->id]) }}" title="{{{ $topic->category->name }}}">
          {{{ $topic->category->name }}}
        </a>
        <span> • </span>
        {{ $topic->reply_count }} {{ lang('Replies') }}
        <span> • </span>
        <span class="timeago">{{ $topic->created_at }}</span>

      </span>

  </li>
  @endforeach

</ul>